### PR TITLE
setup unit testing

### PR DESCRIPTION
**Pull request by hbapte**

### CODE REVIEW

**Review by ProgrammerDATCH — CHANGES_REQUESTED** [review]
You didn't refer to new changes in `develop` branch.
I think those tests are no longer needed considering new structure we have, we only need test for /, 

Also there is conflicts in your commit, simply because you didn't pull latest changes from `develop` branch.

Just pull new changes and remove unnecessary changes then resolve conflicts and re-submit pull request.   

Happy Coding.

**Review by ProgrammerDATCH — APPROVED** [review]
Looks clean now.

**Review by ProgrammerDATCH — COMMENTED** [review]
Some tests are failing on Circle CI, I looked through and noticed that tests you wrote before are interfering,

Check how you can resolve, or simply since no any changes your commit brings I advice u to delete this branch.

**Comment by AimePazzo** [comment]
Your tests are failing. Please take a look at why

**Review by AimePazzo — CHANGES_REQUESTED** [review]
there is duplicate in your code `chai.request(app)`

**Comment by hbapte** [comment]
> Your tests are failing. Please take a look at why

there is change in test script `package.json`

**Pull request closed without merging**
